# Generated by Django 5.2.1 on 2025-05-13 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nazionalità',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='campionato',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nazionalità', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campionati', to='transfermarkt.nazionalità')),
            ],
        ),
        migrations.CreateModel(
            name='squadra',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data_fondazione', models.DateField(null=True)),
                ('stadio', models.CharField(max_length=100, null=True)),
                ('capacita_stadio', models.IntegerField(null=True)),
                ('città', models.CharField(max_length=100, null=True)),
                ('campionato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squadre', to='transfermarkt.campionato')),
            ],
        ),
        migrations.CreateModel(
            name='partita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('stadio', models.CharField(max_length=100)),
                ('gol_casa', models.IntegerField(blank=True, null=True)),
                ('gol_ospite', models.IntegerField(blank=True, null=True)),
                ('campionato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partite', to='transfermarkt.campionato')),
                ('squadra_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partite_casa', to='transfermarkt.squadra')),
                ('squadra_ospite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partite_ospite', to='transfermarkt.squadra')),
            ],
        ),
        migrations.CreateModel(
            name='giocatore',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField(null=True)),
                ('valore_mercato', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ruolo', models.CharField(max_length=100, null=True)),
                ('nazionalità', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giocatori', to='transfermarkt.nazionalità')),
                ('squadra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giocatori', to='transfermarkt.squadra')),
            ],
        ),
        migrations.CreateModel(
            name='utente',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('data_nascita', models.DateField(null=True)),
                ('nazionalità', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utenti', to='transfermarkt.nazionalità')),
                ('squadra_preferita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utenti', to='transfermarkt.squadra')),
            ],
        ),
    ]
