# Generated by Django 5.2.1 on 2025-05-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfermarkt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nazionalità',
            new_name='Nazionalita',
        ),
        migrations.RenameField(
            model_name='campionato',
            old_name='nazionalità',
            new_name='nazionalita',
        ),
        migrations.RenameField(
            model_name='giocatore',
            old_name='nazionalità',
            new_name='nazionalita',
        ),
        migrations.RenameField(
            model_name='squadra',
            old_name='città',
            new_name='citta',
        ),
        migrations.RenameField(
            model_name='utente',
            old_name='nazionalità',
            new_name='nazionalita',
        ),
    ]
