# Generated by Django 5.2.1 on 2025-05-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfermarkt', '0002_rename_nazionalità_nazionalita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='id',
        ),
        migrations.AlterField(
            model_name='utente',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
