# Generated by Django 5.2.1 on 2025-05-14 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfermarkt', '0003_remove_utente_id_alter_utente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='partita',
            name='risultato',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Giornata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('campionato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giornate', to='transfermarkt.campionato')),
            ],
        ),
        migrations.AddField(
            model_name='partita',
            name='giornata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partite', to='transfermarkt.giornata', to_field='numero'),
        ),
    ]
