# Generated by Django 5.2.1 on 2025-05-14 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfermarkt', '0004_partita_risultato_giornata_partita_giornata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giornata',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partita',
            name='giornata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partite', to='transfermarkt.giornata'),
        ),
        migrations.AlterUniqueTogether(
            name='giornata',
            unique_together={('numero', 'campionato')},
        ),
    ]
