# Generated by Django 5.2 on 2025-05-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfermarkt', '0005_alter_giornata_numero_alter_partita_giornata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='giocatore',
            name='assist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giocatore',
            name='cartellini_gialli',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giocatore',
            name='cartellini_rossi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giocatore',
            name='contratto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giocatore',
            name='gol_fatti',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giocatore',
            name='presenze',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='squadra',
            name='data_fondazione',
            field=models.DateField(blank=True, null=True),
        ),
    ]
