# Generated by Django 5.2.1 on 2025-05-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfermarkt', '0006_admin_giocatore_assist_giocatore_cartellini_gialli_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giornata',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
