# Generated by Django 5.2.1 on 2025-05-20 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfermarkt', '0007_alter_giornata_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='classifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posizione', models.IntegerField()),
                ('punti', models.IntegerField()),
                ('gol_fatti', models.IntegerField()),
                ('gol_subiti', models.IntegerField()),
                ('differenza_reti', models.IntegerField()),
                ('partite_giocate', models.IntegerField()),
                ('partite_vinte', models.IntegerField()),
                ('partite_pareggiate', models.IntegerField()),
                ('partite_perse', models.IntegerField()),
                ('campionato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifiche', to='transfermarkt.campionato')),
                ('squadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifiche', to='transfermarkt.squadra')),
            ],
            options={
                'unique_together': {('squadra', 'campionato')},
            },
        ),
    ]
